### ISSUE TITLE
The road to launch.

### ISSUE THREAD

**Issue by d-shaktiranjan** [d-shaktiranjan/destructure-backend#19]
## Authentication

-   [x] Login with google #2
-   [x] Google Call back #2
-   [x] Dynamic google redirect after login #20
-   [x] Logout #2

## Blog

-   [x] co-author #22

### Admin

-   [x] Create #4
-   [x] Update #4
-   [x] Get List #4
-   [x] Get blog detail page #4
-   [x] Generate unique slug #31
-   [x] Route for checking slug is unique or not #31

### User

-   [x] Get List #4
-   [x] Get blog detail page #4
-   [x] Get blog list reaction record for logged user #14

### User

-   [x] Add comment #16
-   [x] Update comment #27
-   [x] Delete comment #16
-   [x] Comment & reply list #32
-   [x] Reply to a comment #35

### On Blog

-   [x] Add reaction #8
-   [x] Alter reaction #8
-   [x] Remove reaction #8

### On Comment

-   [x] Add reaction #36 
-   [x] Alter reaction #36 
-   [x] Remove reaction #36 
-   [x] Add reaction count & given status #37

## File

-   [x] Store in local #6
-   [x] Serve static file #24

## Search

-   [x] search lib & model. #55 
-   [x] store search query. #55 
-   [x] route for user's query list. #55
-   [x] route for remove search history. #55
-   [x] route to update blog visit after search. #55
